//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public int OrderID { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Description { get; set; }
    }
}
